sudo: false
dist: bionic
language: python
python: 3.7
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - black --check **/*.py
  - pipenv run lint
  - pipenv run tests
  - pipenv run render
  - cd $TRAVIS_BUILD_DIR
deploy:
    provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    local_dir: public
    on:
        branch: master
after_success:
  - codecov
