name: Build

on:
  pull_request:
    branches: [ deploy ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - name: Build Site
      run: npm run build
