name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rode
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - name: Build Site
      run: npm run build
    - name: Deploy with Github Pages
      run: npm run deploy
