name: Linting

on: [ push ]

jobs:
  super_linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          DEFAULT_BRANCH: deploy
  flake8_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout py-planner
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pipenv
      - name: Lint with flake8
        run: pipenv run lint --statistics

  black_format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout py-planner
        uses: actions/checkout@master
      - name: Install Black
        run: |
          python3 -m pip install --upgrade pip
          pip install black
      - name: Check Formatting with Black
        run: black --check .

  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout py-planner
        uses: actions/checkout@master
      - name: Install markdown lint cli
        run: npm install -g markdownlint-cli
      - name: Lint Markdown
        run: markdownlint **/*.md
